version: '3'

includes:
  docker: ./scripts/taskfiles/DockerTasks.yml
  windows: ./scripts/taskfiles/WindowsTasks.yml
  linux: ./scripts/taskfiles/LinuxTasks.yml
  frontend: ./scripts/taskfiles/FrontendTasks.yml

vars:
  VERSION: 0.0.1
  PROJECT_DIR:
    sh: pwd | sed 's/\\/\//g'
  ISRELEASE: true

tasks:

  default:
    desc: Show available tasks for this project
    cmds:
      - task -l

  run:
    desc: Run the project
    dir: ./
    cmds:
      - air -c .air.toml

  release:
    desc: Release the project
    deps: [ build ]
    summary: |
      Release the project to github

      It will build your project before starting the release.
      Please make sure that you have set GITHUB_TOKEN before starting.
    cmds:
      - goreleaser

  build:
    desc: Build the project
    cmds:
      - goreleaser release --skip-publish

  clean:
    desc: Clean the project
    cmds:
      - task: windows:clean-win-amd64
      - task: windows:clean-win-386

  dl-deps:
    desc: Install tools required to build this app
    cmds:
      - go install github.com/goreleaser/goreleaser@latest
      - task: go-get
        vars: { REPO: github.com/go-semantic-release/semantic-release }

  go-get:
    cmds:
      - go get -u {{.REPO}}
