version: '3'

includes:
  docker: ./.tasks/DockerTasks.yml
  windows: ./.tasks/WindowsTasks.yml
  linux: ./.tasks/LinuxTasks.yml
  frontend: ./.tasks/FrontendTasks.yml

vars:
  VERSION: 0.0.1
  PROJECT_DIR:
    sh: pwd | sed 's/\\/\//g'
  ISRELEASE: true

tasks:

  default:
    desc: Show available tasks for this project
    cmds:
      - task -l

  deps:
    desc: Install all developer depencies for this project
    cmds:
      - task: install-go-releaser
      - npm install

  run:
    desc: Run the project in dev mode
    dir: ./
    cmds:
      - air -c ./.configs/.air.toml

  build:
    desc: Build the project
    cmds:
      - goreleaser build -f ./.configs/.goreleaser.yaml --rm-dist

  release:
    desc: Release the project
    cmds:
      - npx -p @semantic-release/changelog -p @semantic-release/exec -p @semantic-release/git semantic-release

  install-go-releaser:
    desc: Install GoReleaser - https://goreleaser.com/
    cmds:
      - go install github.com/goreleaser/goreleaser@latest

  print-os:
    cmds:
      - echo '{{OS}} {{ARCH}}'
      - echo '{{if eq OS "windows"}}windows-command{{else}}unix-command{{end}}'
      # This will be path/to/file on Unix but path\to\file on Windows
      - echo '{{fromSlash "path/to/file"}}'
