version: '3'

includes:
  docker: ./scripts/taskfiles/DockerTasks.yml
  windows: ./scripts/taskfiles/WindowsTasks.yml
  linux: ./scripts/taskfiles/LinuxTasks.yml
  frontend: ./scripts/taskfiles/FrontendTasks.yml

vars:
  VERSION: 0.0.1
  PROJECT_DIR:
    sh: pwd | sed 's/\\/\//g'
  ISRELEASE: true

tasks:

  default:
    desc: Show available tasks for this project
    cmds:
      - task -l

  run:
    desc: Run the project in dev mode
    dir: ./
    cmds:
      - air -c ./config/.air.toml

  build:
    desc: Build the project
    cmds:
      - goreleaser build --rm-dist

  release:
    desc: Release the project
    deps: [ build ]
    cmds:
      - goreleaser release



  dl-deps:
    desc: Install GoReleaser - https://goreleaser.com/
    cmds:
      - go install github.com/goreleaser/goreleaser@latest

  print-os:
    cmds:
      - echo '{{OS}} {{ARCH}}'
      - echo '{{if eq OS "windows"}}windows-command{{else}}unix-command{{end}}'
      # This will be path/to/file on Unix but path\to\file on Windows
      - echo '{{fromSlash "path/to/file"}}'
