name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  #lint:
  #  name: Lint
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #    - uses: actions/setup-go@v3
  #      with:
  #        go-version: 1.18
  #    - uses: golangci/golangci-lint-action@v3

  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    #needs: lint
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: go build ./cmd/qst/
        env:
          CGO_ENABLED: 1
      - run: go test -v ./...

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: cd ./web && npm install && npm run lint && npm run build
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          hooks: goreleaser
          prerelease: true
          update-file: ./web/package.json
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          CGO_ENABLED: 1
