name: CI
on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:

  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: go build ./cmd/qst/
        env:
          CGO_ENABLED: 1
      - run: go test -v ./...


  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # Make sure we don't use the generated github token
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - run: cd ./web && npm install && npm run lint && npm run build
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          hooks: goreleaser
          prerelease: true
          allow-initial-development-versions: true
          update-file: package.json
          changelog-generator-opt: "emojis=true"
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          CGO_ENABLED: 1
