# Quantstop Orderbook Release Workflow

name: Release

on:

  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false # Make sure we don't use the generated github token

      # Set up Go actions
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      # Set up Node.js actions
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install Task tool - https://taskfile.dev/
      - name: Install Task tool
        run: go install github.com/go-task/task/v3/cmd/task@latest

      # Install all dependencies using Task
      - name: Install Dependencies
        run: task deps

      # Run Release Task
      - name: Release
        env:
          # Use custom release token and set git names for semantic-release
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: sudoshu
          GIT_AUTHOR_EMAIL: sudoshu@protonmail.com
          GIT_COMMITTER_NAME: sudoshu
          GIT_COMMITTER_EMAIL: sudoshu@protonmail.com
        run: task release
