# Quantstop Orderbook Release Workflow

name: Release

on:

  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --all # Re-pull the repo to get the latest tags

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      # Run the SVU tool to generate tags
      - name: Run SVU
        run: |
          go get github.com/caarlos0/svu
          go install github.com/caarlos0/svu
          git tag $(svu next)

      # Cleanup go.mod from previous step
      - name: Cleanup go.mod
        run: go mod tidy

      # Run the GoReleaser tool
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
