# Quantstop Orderbook Release Workflow

name: Release

# Controls when the workflow will run
on:

  # Triggers the workflow to run on push events for the specified branches
  push:
    branches: [ "release" ]

  # Triggers the workflow to run on push events for the specified branches
  pull_request:
    branches: [ "release" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Control permissions for the workflow
permissions:
  contents: write
  # packages: write
  # issues: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "release"
  release:

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Fetch the git tags
      - run: git fetch --force --tags

      # Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      #- name: Install Build Tools - Task
      #  run: go install github.com/go-task/task/v3/cmd/task@latest

      #- name: Install Build Tools - goversioninfo
      #  run: go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

      # Build Go project
      #- name: Build
      #  run: task build

      # Test Go project
      #- name: Test
      #  run: go test -v ./...

