# Quantstop Orderbook Release Workflow

name: Release

on:

  # Triggers the workflow on push or pull request events but only for the release branch
  push:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Make sure the release step uses its own credentials.
          persist-credentials: false

      # Set up Go actions
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      # Set up Node.js actions
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      # Install Task tool - https://taskfile.dev/
      - name: Install Task tool
        run: go install github.com/go-task/task/v3/cmd/task@latest

      # Install all dependencies using Task
      - name: Install Dependencies
        run: task deps

      # Run Release Task
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: task release
